title       = "gitview"
baseURL     = "https://gitview.tamnd.com/"
description = "Browse any git repository in your browser with a UI that looks and feels like github.com. One binary, read only, no setup."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/gitview"
